root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"

  include_ext = ["go"]
  exclude_dir = ["tmp", "gen", "migrations", "bin"]
  delay = 1000

  send_interrupt = true

[log]
  time = false
